Dende\KaloszBundle\Entity\Analysis:
    type: entity
    table: analysis
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
        description:
            type: string
            length: 45
            fixed: false
            nullable: true
    oneToOne:
        movie:
            targetEntity: Movies
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                movie_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
